module.exports = [
//  {enabled: true, job: x, group:  x, replace: xxxxxx, instance: true, Description:""},
	// 0-warrior 双刀
	{enabled: true, job: 0, group:  1, replace:  11200, instance: true, Description:"連續攻擊"},
	{enabled: true, job: 0, group: 19, replace: 191101, instance: true, Description:"特質連打 -> 2段"},
	{enabled: true, job: 0, group: 40, replace: 400122, instance: true, Description:"二段劍舞 -> 2段"},
	{enabled: true, job: 0, group: 41, replace: 410131, instance: true, Description:"縱斷劈擊 -> 2段"},
	{enabled: true, job: 0, group: 42, replace: 420130, instance: true, Description:"刀刃暴風 -> 2段"},
	{enabled: true, job: 0, group: 31, replace: 310830, instance: true, Description:"破烈"},
	{enabled: true, job: 0, group:  4, replace: 360130, instance: true, Description:"旋風擊"},
	{enabled: true, job: 0, group: 36, replace: 360130, instance: true, Description:"旋風擊"},
	{enabled: true, job: 0, group: 29, replace: 370130, instance: true, Description:"無雙亂舞 劈擊"},
	{enabled: true, job: 0, group: 37, replace: 370130, instance: true, Description:"無雙亂舞 劈擊"},
	{enabled: true, job: 0, group: 30, replace: 380130, instance: true, Description:"疾風劈擊"},
	{enabled: true, job: 0, group: 38, replace: 380130, instance: true, Description:"疾風劈擊"},
	// 1-lancer 枪骑
	// {enabled: true, job: 1, group:  1, replace:  11200, instance: true, Description:"連續攻擊XII -> 1段"},
	{enabled: true, job: 1, group:  3, replace:  30200, instance: true, Description:"猛烈突進II  -> 加速"},
	{enabled: true, job: 1, group:  5, replace:  50130, instance: true, Description:"盾牌打擊I   -> 加速"},
	{enabled: true, job: 1, group: 10, replace: 100330, instance: true, Description:"粉碎防具III -> 强力"},
	{enabled: true, job: 1, group: 13, replace: 131130, instance: true, Description:"跳躍攻擊XI  -> 加速"},
	{enabled: true, job: 1, group: 18, replace: 181101, instance: true, Description:"盾牌連打XI  -> 2段 无CD"},
	{enabled: true, job: 1, group: 21, replace: 210402, instance: true, Description:"衝擊猛打IV  -> 加速"},
	{enabled: true, job: 1, group: 25, replace: 251030, instance: true, Description:"壓倒X       -> 加速"},
	{enabled: true, job: 1, group: 28, replace: 280101, instance: true, Description:"正義跳躍I   -> 加速"},
	// 2-slayer 大剑
	// {enabled: true, job: 2, group:  1, replace:  11200, instance: true, Description:"連續攻擊XII -> 1段"},
	{enabled: true, job: 2, group:  2, replace:  21130, instance: true, Description:"重擊斬XI    -> 加速"},
	{enabled: true, job: 2, group:  4, replace:  40200, instance: true, Description:"緊急迴避II  -> 1段 无CD"},
	{enabled: true, job: 2, group: 12, replace: 121102, instance: true, Description:"要害攻擊XI  -> 加速"},
	{enabled: true, job: 2, group:  8, replace:  81030, instance: true, Description:"一刀兩斷X   -> 加速"},
	{enabled: true, job: 2, group: 23, replace: 230930, instance: true, Description:"瞬閃IX      -> 加速"},
	{enabled: true, job: 2, group: 24, replace: 240930, instance: true, Description:"下巴粉碎IX  -> 加速"},
	{enabled: true, job: 2, group: 25, replace: 250130, instance: true, Description:"真•一刀兩斷 -> 加速"},
	{enabled: true, job: 2, group: 26, replace: 260130, instance: true, Description:"斬擊        -> 加速"},
	// 3-berserker 斧头
{enabled: false, job: 3, group:  3, replace:  31113, instance: true, Description:"聚力之擊XI  -> 4段"},
{enabled: false, job: 3, group: 10, replace: 101113, instance: true, Description:"龍捲風XI    -> 4段"},
	// 4-sorcerer 魔道
	{enabled: true, job: 4, group:  4, replace: 330112, instance: true, Description:"爆裂球"},
	{enabled: true, job: 4, group:  6, replace: 320100, instance: true, Description:"隕石墜落"},
	{enabled: true, job: 4, group: 34, replace: 340230, instance: true, Description:"魔力強化"},
	{enabled: true, job: 4, group: 36, replace: 360600, instance: true, Description:"元素融合"},
	// 5-archer 弓箭
{enabled: false, job: 5, group:  3, replace:  31113, instance: true, Description:"集中射擊XI  -> 4段"},
{enabled: false, job: 5, group:  4, replace:  41213, instance: true, Description:"穿透射擊XII -> 4段"},
	// 6-priest 祭师
	{enabled: true, job: 6, group:  3, replace:  30730, instance: true, Description:"治癒之風VII  -> 强力"},
	{enabled: true, job: 6, group: 11, replace: 111102, instance: true, Description:"懲罰帳幕XI   -> 强力"},
	{enabled: true, job: 6, group: 16, replace: 161121, instance: true, Description:"審判之手XI   -> 强力"},
	{enabled: true, job: 6, group: 27, replace: 271121, instance: true, Description:"懲罰之手XI   -> 强力"},
	{enabled: true, job: 6, group: 40, replace: 401020, instance: true, Description:"神之氣息X    -> 强力"},
{enabled: false, job: 6, group: 28, replace: 280213, instance: true, Description:"全神卷軸     -> 4段"},
	{enabled: true, job: 6, group: 42, replace: 420130, instance: true, Description:"燦爛的閃爍   -> 强力"},
	// 7-mystic 元素
	// {enabled: true, job: x, group:  x, replace: xxxxxx, instance: true, Description:""},
	// 8-reaper 飞镰
	{enabled: true, job: 8, group: 11, replace: 110203, instance: true, Description:"暗黑鞭II    -> 4段 无CD"},
	{enabled: true, job: 8, group:  3, replace:  30341, instance: true, Description:"飛劍劈擊III -> 强力"},
	{enabled: true, job: 8, group: 15, replace: 150380, instance: true, Description:"反擊III     -> 2段 强力"},
	{enabled: true, job: 8, group: 40, replace: 400100, instance: true, Description:"瞬間跳躍I   -> 1段 无CD"},
	
	{enabled: true, job: 8, group:  4, replace:  40331, instance: true, Description:"強化飛劍最後的一擊"},
	{enabled: true, job: 8, group:  5, replace:  50332, instance: true, Description:"飛劍重擊斬"},
	{enabled: true, job: 8, group:  6, replace:  60242, instance: true, Description:"飛劍揮舞 -> 2段"},
	{enabled: true, job: 8, group:  8, replace:  80230, instance: true, Description:"飛劍迴旋刀刃"},
	{enabled: true, job: 8, group: 10, replace: 100230, instance: true, Description:"飛劍向上揮擊"},
	{enabled: true, job: 8, group: 12, replace: 120231, instance: true, Description:"強化暗黑爆炸"},
	// 9-gunner 魔工
	{enabled: true, job: 9, group:  1, replace: 420101, instance: true, Description:"神秘光束砲擊"},
	{enabled: true, job: 9, group:  5, replace:  51021,    combo: true, Description:"神秘光束連射"},
	{enabled: true, job: 9, group:  9, replace:  93112, instance: false,Description:"發射秘傳導彈"},
	{enabled: true, job: 9, group: 13, replace: 440101, instance: false,Description:"殲滅之光"},
	{enabled: true, job: 9, group: 40, replace: 400102, instance: true, Description:"爆衝 裝填導彈 -> 1段"},
	{enabled: true, job: 9, group: 43, replace: 430151, instance: true, Description:"神秘光線 -> 2段"},
	// 10-brawler 拳师
	{enabled: true, job:10, group:  1, replace:  21201, instance: true, Description:"強打 -> 1段"},
	{enabled: true, job:10, group:  4, replace:  41130, instance: true, Description:"地面強打"},
	{enabled: true, job:10, group: 22, replace: 220130, instance: true, Description:"迴旋飛踢"},
	{enabled: true, job:10, group: 26, replace: 260102, instance: true, Description:"颱風連打 -> 3段"},
	{enabled: true, job:10, group: 40, replace: 400100, instance: true, Description:"瞬閃 -> 1段"},
	// 11-ninja 忍者
	{enabled: true, job:11, group:  1, replace: 150732, instance: true, Description:"多重分身火焰術 -> 1段"},
	{enabled: true, job:11, group:  2, replace:  20100, instance: true, Description:"迴避啟動 -> 1段"},
	{enabled: true, job:11, group:  3, replace:  30840, instance: true, Description:"標槍連射"},
	{enabled: true, job:11, group:  8, replace:  80252, instance: true, Description:"多重分身爆炎術"},
	{enabled: true, job:11, group: 21, replace: 210113, instance: true, Description:"迴力鏢手裏劍 -> "},
	{enabled: true, job:11, group: 22, replace: 220140, instance: true, Description:"多重分身機動攻擊術"},
	// 12-valkyrie 月光
	{enabled: true, job:12, group:  8, replace:  85101, instance: true, Description:"滿月 -> 2段"},
	{enabled: true, job:12, group: 15, replace: 245103, instance: true, Description:"狂暴槍術"},
	{enabled: true, job:12, group: 16, replace: 166230, instance: true, Description:"月光的共鳴"},
	{enabled: true, job:12, group: 23, replace: 235102, instance: true, Description:"半月斬 - 1段"},
	{enabled: true, job:12, group: 24, replace: 245102, instance: true, Description:"狂暴槍術 -> 1段"},
	{enabled: true, job:12, group: 25, replace: 250132, instance: true, Description:"開戰 -> 1段"}
]
